core/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class Video(db.Model):

    id = db.Column(db.String(80), primary_key=True)

    title = db.Column(db.String(80), nullable=False)

    without_silence = db.Column(db.Boolean, nullable=False, default=False)

    filename = db.Column(db.String(80), nullable=False)

    def __repr__(self):
        return '<Video {0} Title: "{1}">'.format(self.filename, self.title)

core/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import StringField, BooleanField, validators

import settings


class SubmitFileForm(FlaskForm):

    title = StringField('Title', [validators.Length(min=4, max=80), validators.InputRequired()])

    video = FileField('File', validators=[FileRequired(),
                                          FileAllowed(settings.ALLOWED_EXTENSIONS)])

    without_silence = BooleanField('Remove Silence')

core/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap

import settings
from .models import db
from .backend.routes import mod as backend_mod
from .frontend.routes import mod as frontend_mod

app = Flask(__name__)

app.register_blueprint(frontend_mod)
app.register_blueprint(backend_mod, url_prefix='/api')


def create_app():

    # Database settings
    app.config['SQLALCHEMY_DATABASE_URI'] = settings.SQLALCHEMY_DATABASE_URI
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = settings.SQLALCHEMY_TRACK_MODIFICATIONS

    # Video Settings
    app.config['UPLOAD_FOLDER'] = settings.UPLOAD_FOLDER

    app.config['WTF_CSRF_ENABLED'] = settings.WTF_CSRF_ENABLED
    app.config['SECRET_KEY'] = settings.SECRET_KEY

    Bootstrap(app)

    db.init_app(app)
    db.create_all(app=app)

    return app

core/backend/routes.py
from flask import Blueprint, redirect, url_for, flash

from core.utils import delete_video, get_video_to_download, process_video

mod = Blueprint("backend", __name__)


@mod.route('/videos/<video_id>/download/', methods=['GET'])
def get_video(video_id):
    try:
        video = get_video_to_download(video_id)
    except Exception as e:
        flash('An error happen while downloading the video. Please try again later.', category='danger')
        return redirect(url_for('frontend.home_page'))
    else:
        return video


@mod.route('/videos/<video_id>/delete/', methods=['GET'])
def delete_video_by_id(video_id):
    try:
        delete_video(video_id)
        flash('Video deleted with success', category='success')
    except Exception as e:
        flash('An error happen while deleting. Please try again later.', category='danger')
    return redirect(url_for('frontend.home_page'))


@mod.route('/videos/<video_id>/process-video/', methods=['GET'])
def process_video_by_id(video_id):
    try:
        process_video(video_id)
        flash('Video process with success', category='success')
    except Exception as e:
        flash('An error happen while processing. Please try again later.', category='danger')
    return redirect(url_for('frontend.home_page'))


@mod.route('/videos/<video_id>/download-processed/', methods=['GET'])
def get_video_without_silence(video_id):
    try:
        video = get_video_to_download(video_id, 'processed')
        flash('Video process with success', category='success')
    except Exception as e:
        flash('An error happen while processing. Please try again later.', category='danger')
        return redirect(url_for('frontend.home_page'))
    else:
        return video

core/frontend/routes.py
from flask import Blueprint, render_template, request, flash

from core.forms import SubmitFileForm
from core.utils import get_videos_dict, save_video

mod = Blueprint("frontend", __name__)


@mod.route('/', methods=['GET', 'POST'])
def home_page():
    form = SubmitFileForm()
    if request.method == 'POST' and form.validate_on_submit():
        try:
            save_video(form.title.data, form.video.data, form.without_silence.data)
            flash('Video saved with success', category='success')
        except Exception as e:
            flash('An error happen while adding the video. Please try again later.', category='danger')
    return render_template('index.html', videos=get_videos_dict(), form=form)

core/templates/index.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Video Silencer Application{% endblock %}

{% block navbar %}
<div class="navbar navbar-fixed-top">
</div>
{% endblock %}

{% block content %}

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h1>Video Silencer Application</h1>
        </div>
    </div>

    {% if videos %}
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <table class="table table-striped table-bordered table-hover">
                <tr>
                    <th>Title</th>
                    <th>Filename</th>
                    <th>Actions</th>
                </tr>
                {% for video in videos %}
                    <tr>
                        <td>{{ video.title }}</td>
                        <td>{{ video.filename }}</td>
                        <td>
                            <!-- Single button -->
                            <div class="btn-group">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li><a href="{{url_for('backend.get_video', video_id=video.id )}}">Download with silence</a></li>
                                    {% if video.without_silence %}
                                        <li><a href="{{url_for('backend.get_video_without_silence', video_id=video.id )}}">Download without silence</a></li>
                                    {% else %}
                                        <li><a href="{{url_for('backend.process_video_by_id', video_id=video.id )}}">Process Video</a></li>
                                    {% endif %}
                                    <li role="separator" class="divider"></li>
                                    <li><a href="{{url_for('backend.delete_video_by_id', video_id=video.id )}}">Delete</a></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    {% endif %}

    <div class="container">
        <h3>Sumbit New Video</h3>
        <form method="post" action="{{url_for('frontend.home_page')}}" enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ wtf.form_field(form.title) }}
            {{ wtf.form_field(form.video) }}
            {{ wtf.form_field(form.without_silence) }}
            <input class="btn btn-primary" type=submit value=Add>
        </form>
    </div>

{% endblock %}